package edu.mines.jjj.peopledb;

import java.util.ArrayList;

public class Person
{
	public static class PersonBuilder
	{
		private String firstName, lastName, username;
		private Gender gender;
		private Relationship relationship;
		private int age;
		
		public PersonBuilder()
		{
		}
		
		public PersonBuilder(ArrayList<String> info)
		{
			this.firstName = info.get(0);
			this.lastName = info.get(1);
			this.username = info.get(2);
			this.gender = Gender.fromString(info.get(3));
			this.relationship = Relationship.fromString(info.get(4));
			
		}
		
		public Person build()
		{
			return new Person(this);
		}
		
		public PersonBuilder firstName(String firstName)
		{
			this.firstName = firstName;
			return this;
		}
		
		public PersonBuilder gender(Gender gender)
		{
			this.gender = gender;
			return this;
		}
		
		public String getFirstName()
		{
			return firstName;
		}
		
		public Gender getGender()
		{
			return gender;
		}
		
		public String getLastName()
		{
			return lastName;
		}
		
		public Relationship getRelationship()
		{
			return relationship;
		}
		
		public String getUsername()
		{
			return username;
		}
		
		public PersonBuilder lastName(String lastName)
		{
			this.lastName = lastName;
			return this;
		}
		
		public PersonBuilder relationship(Relationship relationship)
		{
			this.relationship = relationship;
			return this;
		}
		
		public PersonBuilder username(String username)
		{
			this.username = username;
			return this;
		}
		
		public PersonBuilder age(int age)
		{
			this.age = age;
			return this;
		}
		
		public int getAge()
		{
			return age;
		}
		
	}
	
	private final ArrayList<Person> friends;
	private final PeopleDB db;
	private final String firstName, lastName, username;
	private final Gender gender;
	private final Relationship relationship;
	private int age;
	
	public Person(PersonBuilder builder)
	{
		this.firstName = builder.getFirstName();
		this.lastName = builder.getLastName();
		this.username = builder.getUsername();
		this.gender = builder.getGender();
		this.relationship = builder.getRelationship();
		this.age = builder.getAge();
		friends = new ArrayList<Person>();
		db = PeopleDB.getInstance();
	}
	
	public void addFriend(Person newFriend)
	{
		if (!friends.contains(newFriend))
			friends.add(newFriend);
	}
	
	public String getFirstName()
	{
		return firstName;
	}
	
	public Gender getGender()
	{
		return gender;
	}
	
	public String getLastName()
	{
		return lastName;
	}
	
	public Relationship getRelationship()
	{
		return relationship;
	}
	
	public String getUsername()
	{
		return username;
	}
	
	public int getAge()
	{
		return age;
	}
	
	public void update()
	{
		db.insertPerson(this);
	}
	
	// auto generated by eclipse
	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + age;
		result = prime * result + ((firstName == null) ? 0 : firstName.hashCode());
		result = prime * result + ((friends == null) ? 0 : friends.hashCode());
		result = prime * result + ((gender == null) ? 0 : gender.hashCode());
		result = prime * result + ((lastName == null) ? 0 : lastName.hashCode());
		result = prime * result + ((relationship == null) ? 0 : relationship.hashCode());
		result = prime * result + ((username == null) ? 0 : username.hashCode());
		return result;
	}
	
	// auto generated by eclipse
	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Person other = (Person) obj;
		if (age != other.age)
			return false;
		if (firstName == null)
		{
			if (other.firstName != null)
				return false;
		}
		else if (!firstName.equals(other.firstName))
			return false;
		if (friends == null)
		{
			if (other.friends != null)
				return false;
		}
		else if (!friends.equals(other.friends))
			return false;
		if (gender != other.gender)
			return false;
		if (lastName == null)
		{
			if (other.lastName != null)
				return false;
		}
		else if (!lastName.equals(other.lastName))
			return false;
		if (relationship != other.relationship)
			return false;
		if (username == null)
		{
			if (other.username != null)
				return false;
		}
		else if (!username.equals(other.username))
			return false;
		return true;
	}
	
}
